version: '3.9'

services:
  nginx:
    image: nginx
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - nginx-data:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wbdatabase
      MYSQL_USER: shreyder
      MYSQL_PASSWORD: wb123456
      MYSQL_ROOT_PASSWORD: 12345678
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
    restart: unless-stopped

volumes:
  nginx-data:
  mysql-data:
